server.port=8088

spring.datasource.url=jdbc:h2:file:./data/sesam
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

spring.messages.basename=messages
spring.messages.encoding=UTF-8

security.jwt-secret=Xn2r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C*F)J@NcR
security.token-header=Authorization
security.token-prefix=Bearer
security.token-type=JWT
security.token-issuer=secure-api
security.token-audience=secure-app
security.token-expiration=86400000
security.auth-login-url=/api/authenticate

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gp.se.team.3.1@gmail.com
spring.mail.password=touottjrszhliwfh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

file.base-dir=brand_design
